version: "3"
services:
  server:
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    build: .
    ports:
      - "9010:3000"
    volumes:
      - "./images:/usr/src/app/build/images"
